ublue-os/website

docs/index.md
=> fix: change out video on homepage

.github/workflows/deploy.yml
=> fix(ci): use correct github token for package list builder

docs/codecs.md, mkdocs.yml
I'm submitting this PR before the end of the weekend to improve the documentation for uBlue's codecs. Please feel free to review and make any necessary changes. Thank you!
Fixes #105
=> Add docs for codecs (#105)

docs/index.md, docs/making-your-own.md
General
* Makes the structure clearer
* Adds extra information
Additionally
* Mentions and instructs about [`create-ublue-image`](https://github.com/EinoHR/create-ublue-image)
* Compares `main` and `startingpoint`
* Recommends `startingpoint` by default
You might want to hold off on merging until `startingpoint` is updated to use `yafti` and a `build.sh` file
=> feat: restructure and update `making-your-own`

docs/making-your-own.md
Was previously pointing to kinoite.
=> fix: Correct link to Silverblue documentation

.github/ublue-scan.yml
vauxite-main is the preferred image
=> chore: remove vauxite

docs/CONTRIBUTING.md, mkdocs.yml
=> feat: integrate the TOC

.github/ublue-scan.yml
To avoid people rebasing to it since it doesn't come with anything.
=> fix: remove base images from list

docs/CONTRIBUTING.md
As discussed [here](https://github.com/ublue-os/main/issues/23#issuecomment-1510407388) with @castrojo my notes on how to build locally.
=> docs: add notes about building locally (ublue-os/main#23)

docs/making-your-own.md
=> docs: Link from "Making your own" to "Local Testing"

docs/index.md
=> revert: "feat: add card grid to the index"

docs/index.md
=> feat: add card grid to index page

docs/mission.md
=> docs: remove trailing sentence

mkdocs.yml, poetry.lock, pyproject.toml
https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/
=> feat: enable social card plugin

docs/CONTRIBUTING.md, docs/architecture.md, docs/faq.md, docs/installation.md, docs/making-your-own.md, docs/scope.md
The full name reads cleaner as the display name, sorry to touch so many files at once.
=> docs: replace ublue with Universal Blue

docs/blog/posts/custom-images-can-solve-the-third-party-repo-problem.md, docs/blog/posts/hello-world.md, overrides/partials/comments.html
I'm not too concerned about losing the links to the older ones as the discussions are still in the forum.
=> blog: add comment override and correct past blogs

docs/blog/posts/budgie-and-cinnamon-now-available.md
=> fix: link titles

docs/local-testing.md
=> docs: add upgrade step to "Local Testing"

docs/making-your-own.md
=> docs: "Making your Own" - only one top level title

docs/making-your-own.md
noted down the issues with SDDM + greetd for custom images in the docs for making your own image. Not sure if this is the proper place to put them or if some things need to be reformatted to be more in line with the rest of the docs
=> docs: noted issues regarding SDDM + greetd for custom images

docs/CONTRIBUTING.md
It's placed very high up on the page, to help with discoverability.
=> docs: describe the pull request contribution workflow

docs/making-your-own.md
Edit: It's ready for review now. I ended up doing a bunch of cleanups to the flow of related sections too.
=> docs: updated instructions for making your own startingpoint fork

mkdocs.yml
=> docs: split off make your own into tinkerer's guide

docs/installation.md
Found a small typo while reading over the install docs.
=> fix: typo fix for 'erorr'

docs/CONTRIBUTING.md
Explains how RPM Fusion handles driver updates, and covers checks in pull requests currently failing
=> docs: Update CONTRIBUTING.md with an Nvidia section

docs/faq.md
=> fix: remove immutable faq

docs/blog/posts/cosigned-images-are-here.md
Do not merge, just staging this.
=> feat: add cosign blog

docs/guide/software.md
=> fix: broken pkgs.org link

docs/images/bluefin.md, docs/images/bluefin/admin.md, docs/images/bluefin/developer-experience.md, docs/images/bluefin/framework.md, docs/images/bluefin/index.md, mkdocs.yml
This way we can have nice docs and remove the duplicate info from the readme. Also let's us rev without building the OS.
=> feat(bluefin): break out bluefin docs

docs/images/bluefin/developer-experience.md
=> feat: add mlbox instructions

docs/images/bluefin/developer-experience.md
We're not shipping this any more
=> fix: remove docker-podman mention

docs/guide/codecs.md, docs/guide/just.md, docs/guide/screensharing.md, docs/guide/software.md, docs/guide/thumbnails.md, docs/guide/toolbox.md
Quality of life tweaks and line-level corrections.
=> fix:Proofreading1

docs/images/bluefin/admin.md, docs/images/bluefin/developer-experience.md, docs/images/bluefin/framework.md
Three more articles getting some proofreading TLC
=> fix:additional proofreading

docs/images/bazzite/index.md, docs/images/bazzite/installation.md, docs/images/bazzite/waydroid.md
Keeping formatting consistent for newly updated Bazzite docs.
=> fix:proofreading & QOL improvemnt to Bazzite docs.

docs/guide/just.md
also minor typo fix and reordering
=> docs: correct enroll-secure-boot-key command

docs/images/bazzite/installation.md
Gaming guide will eventually need to be linked to the website's page if it gets there.
=> fix: links to other documentation in installation.md

docs/images/bazzite/gaming_guide.md
Added some more information too.
=> fix: Gaming Guide documentation errors, QoL improvements

docs/media.md
=> feat: add bazzite media mentions

docs/images/bazzite/installation.md
...and Added FAQ Link near the bottom.  Italicized bazzite to match formatting.
=> feat: Video Guide by Hi Tech Lo Life

docs/images/bazzite/installation.md
=> fix: grammar

docs/images/bazzite/FAQ.md
Add instructions to fix Night Mode and color saturation not working during games.
addresses ublue-os/bazzite#179
=> feat: Include information regarding Night Mode and color saturation

docs/blog/posts/bazzite-buzz-01.md
We can change the name to something else if you want, "changelog" sounded boring.
@nicknamenamenick did the bulk of the work so top billing and let's not merge until we get the full ack from them. 
Then we just do these when cool things happen in bazzite.
=> feat: bazzite buzz #1

docs/blog/.authors.yml
This is so your info shows up properly on the blog. Didn't know what you would want as your display name so just added that.
=> feat: add nicknamenick to .authors.yml

docs/images.md
Thought documenting how to pin current deployment might be useful.
=> feat: add step to pin ostree deployment

docs/tinker/fork-your-own.md
This adds an example how to fork your own, but still allow you to contribute to the upstream project. 
Big thanks to @bsherman for suggesting this. Hope this will help others as well.
=> feat: add advanced setup to fork-your-own.md

docs/blog/.authors.yml, docs/blog/posts/startingpoint-rewrite-heads-up.md
This gives a "heads-up" for https://github.com/ublue-os/startingpoint/pull/135 which is basically finished and will be merged soon.
Can y'all do a ping of this on discord #announcements so it doesn't go unnoticed.
=> feat: startingpoint rewrite blog 1

docs/mission.md
=> fix: mission updates

docs/images/bazzite/installation.md
Updated docs with video that just focuses on the OS install.
=> Add 2nd bazzite install video

docs/images/bazzite/FAQ.md
It should be fixed according to Kyle now.
=> chore: remove now fixed night mode question

docs/blog/posts/startingpoint-rewrite-heads-up.md, docs/tinker/modification.md, docs/tinker/modules/bling.md, docs/tinker/modules/files.md, docs/tinker/modules/index.md, docs/tinker/modules/rpm-ostree.md, docs/tinker/modules/script.md, docs/tinker/modules/systemd.md, docs/tinker/modules/yafti.md, mkdocs.yml
This PR should be merged right after https://github.com/ublue-os/startingpoint/pull/135
=> feat: startingpoint rewrite-related docs updates

docs/images/bazzite/FAQ.md
=> feat: talk about rollbacks

docs/images/bazzite/installation.md
=> fix: punctuation consistency

LICENSE
=> feat: explicitly set cc-sa 4 license

docs/media.md
=> fix: fixxed incorrect link

docs/blog/posts/bazzite-buzz-03.md
=> fix: typo in bazzite-buzz-03.md

docs/images/bazzite/FAQ.md
=> fix: specify linux distros can be dual booted IF

docs/images/bazzite/installation.md
and what exactly is categorized as a desktop image.
=> feat: talk about specialized hardware images

docs/blog/posts/bazzite-buzz-03.md
Got some feedback that we should explain what all this is so adding this boilerplate.
=> feat: add description at the top

docs/images/asus.md
=> fix: remove tlp section

docs/blog/posts/bazzite-buzz-04.md
Trying to find a consistent format for these.
=> feat: Create Bazzite Buzz No. 4

docs/media.md
=> feat: Add additonal "News and Websites" for Bazzite

docs/blog/posts/new-hwe-images.md
=> feat: Create new-hwe-images.md

docs/images/bazzite/FAQ.md
Also rearranged "how to rebase images" section.
=> feat: Add documentation on just, yafti, and fleek

docs/images/bazzite/FAQ.md
Also added a link to the linux gaming guide.
=> chore: Re-arranged FAQ

.github/ublue-scan.yml
=> updated to list all non-OS images

docs/blog/posts/bazzite-buzz-05.md
Need to rebase right now until new ISOs.
=> chore: Add details on ASUS and Surface builds

docs/images/bazzite/FAQ.md
=> feat: Mention BIOS updates for Steam Deck

docs/images/bazzite/FAQ.md
Also re-arranged the Linux gaming guide.
=> feat: Add Contributing Documentation Link to FAQ

docs/images/bazzite/CONTRIBUTING.md
Taken from the latest Fedora podcast.
=> feat: Add Lorax and Anaconda Skills in Bazzite's CONTRIBUTING

docs/images/bazzite/installation.md
Only merge this IF the recent PR for the FAQ merges!
=> feat: add warning to installation guide

docs/guide/toolbox.md
=> fix: add double quotes

docs/blog/posts/bazzite-buzz-05.md
Old news now, but it keeps it consistent.
=> fix: Add Bazzite category to Bazzite Buzz #5

docs/images/bazzite/FAQ.md
Also added how to disable automatic updates (not recommended)
=> fix: Update rollback update information

docs/images/bazzite/CONTRIBUTING.md
Added branding in the image too.
=> chore:  A few things on the Contributing Doc

docs/images/bazzite/FAQ.md
Yes, removing them is an unsupported configuration.
=> feat: Add viewing system packages and removing them

docs/images/bazzite/installation.md
Added a screenshot of the installer too.  Removed Wayland/X11 section and moved it to FAQ (another PR.)
=> feat: Two notes at the top

docs/images/bazzite/FAQ.md
Re-arranged some things again too.
=> fix: Add Wayland/X11 differences from Installation

docs/images/bazzite/gaming_guide.md
Might expand on this later too.
=> feat: Modding Quickstart Guide

docs/images/bazzite/FAQ.md
Prepping documentation for the F39 builds coming this Halloween (maybe).
=> fix: grammar, couple of adjustments

docs/images/bazzite/FAQ.md
Doing this to all of the documents, so they look okay for the big 39 release
=> chore: cleanup and revising

docs/images/bazzite/CONTRIBUTING.md
=> chore: remove gum-related contributions

docs/blog/posts/bazzite-buzz-06.md
...so No. 5 wasn't the last newsletter for F38 Bazzite builds.
=> feat: Bazzite Buzz No. 6

docs/cheatsheet/distrobox.md, docs/cheatsheet/just.md, docs/cheatsheet/ostree.md, mkdocs.yml
Initial page with some examples.
fixes #305
=> Add initial cheatsheet page

docs/images/bazzite/index.md
From [#476](https://github.com/ublue-os/bazzite/issues/476)
=> fix: Showcase

docs/images/bazzite/FAQ.md
Really want to make sure the FAQ is nearly perfect at this point.
=> chore: More details and some fixes

docs/images/bluefin/index.md
This should fix: https://github.com/ublue-os/main/issues/403
=> fix: clarify rebasing instructions from upstream

docs/images/bazzite/FAQ.md
=> feat: Added Dual Boot guide for one drive (Thanks ChaiQi!)

docs/images/bazzite/FAQ.md
chore: cleanup and additional information
=> feat: Rename title to Frequently Asked Questions

docs/images/bazzite/installation.md
Should be fine now until something changes with the installer.
=> chore: grammar, minor fixes

docs/images/bazzite/FAQ.md
I don't know how that happened.
=> fix: indent in FAQ

docs/images/bazzite/FAQ.md
I know I just merged changes, but I hope this is the last mistake I notice.   Github preview not being accurate to what actually displays on the webpage.  :pray: hopefully this is it because it's time to focus on the newsletter.
=> fix: Formatting

docs/blog/posts/bazzite-20.md
=> feat: Bazzite two-point-oh

docs/images/bazzite/FAQ.md
chore: give an example of rebasing to a build within the last 90 days
=> fix: Rebase from KINOITE only to prevent issues with GNOME

docs/images/bazzite/FAQ.md
Someone fixed their installer issues by booting it with UEFI supposedly.
=> chore: One more alternative fix for installation issues

docs/images/bazzite/FAQ.md
chore: cleanup
Since we're moving to Discourse for documentation and blog posts on Bazzite, I organized the FAQ so each question is under the appropriate category.
=> chore: Organized FAQ by category

docs/blog/posts/bazzite-buzz-02.md
Great idea but sadly too much has changed since these released and require manual intervention.
=> fix: Add warning to offline installer

docs/tinker/setup/auto-web.md
Not sure how to replace this when the discussion seems to be gone.
=> fix: broken link

docs/index.md
=> fix: Broken link to Legion on Home Page

docs/images/main.md
I don't know why this in here but it shouldn't be.
=> fix: don't recommend -base as a server image

docs/images.md
Updating the community link to point to where GH will redirect you
=> chore: Update community images link

docs/images.md, docs/index.md, docs/tinker/community.md
This PR does two things:
- Fixes all community links (error with last PR)
- runs linter on md file
---
EDIT: If linting is not preffered, i will remove
=> fix: fix community links; run lint on md file

docs/CONTRIBUTING.md
Add more pull request guidance
=> feat: update CONTRIBUTING.md
