ublue-os/website

- docs/faq.md
This copies the documentation from ublue-os/main#61 to the website, so it is more discoverable.
> feat: ublue-os/main#61 documentation to the website

- mkdocs.yml
This makes it so if you click on "Installation" it'll load installation.md instead of having it as a sub-menu item
> fix: Installation link

- docs/making-your-own.md
this is to prevent startingpoint from getting create-ublue-image related issues in the future, and to get people to checkout the readme for troubleshooting steps
> feat: link to create-ublue-image for troubles w it

- docs/guide/software.md
We want flatpak and toolbox to be options ahead of rpm-ostree
> docs: move rpm-ostree to the bottom

- docs/making-your-own.md
The `startingpoint` repo went through a branch restructuring making it necessary for the user to create a `live` branch when setting up their repo.
Extra: Point to the startingpoint-specific docs in, and remove incorrect information from, the "Modification" section.
> docs: add live/template branch step in startingpoint

- docs/guide/just.md
- mkdocs.yml
* Explains what just is and what the purpose of the different justfiles is
* Mentions the --unstable flag
* Recommends to use includes
This is related to https://github.com/ublue-os/config/pull/49 and merging that PR should be done before merging this one.
> docs: add a page about `just`

- mkdocs.insiders.yml
- mkdocs.yml
Allows easier testing from contributors who don't have mkdocs-material-insiders
> fix: move search plugin from mkdocs.insiders.yml to mkdocs.yml

- .github/ublue-scan.yml
We don't want things from the experimental repo listed on the page
> feat: add silverblue-experimental to blocklist

- docs/guide/software.md
Add a line in the documentation to refer to the installation instructions for Fleek, so that users aren't surprised that the commands are missing in their image when they try them out.
> docs: clarify fleek installation requirement

- docs/images.md
Without this fix, the command produces: `error: Unknown command 'ostree-unverified-registry:ghcr.io/ublue-os/silverblue-main'`
> add missing rpm-ostree command

- .github/workflows/links.yml
This will still be useful but not block merges during timeouts.
> chore(ci): loosen up the link check

- docs/images/bazzite/FAQ.md
Also, can the FAQ appear on the main website under Bazzite - https://universal-blue.org/images/bazzite/ 
It will be easier to find then finding it from the installation guide, unless there's a reason not to.
> feat: add why is it called Bazzite and fix formatting

- docs/tinker/setup/manual.md
This tool isn't provided by default, people should default to the webui
> fix: move gh cli app below webui

- docs/blog/posts/startingpoint-rewrite-heads-up.md
* List indentation
* Better PR review call to action
Remaining minor bug that is another mkdocs peculiarity:
* The `#` symbols at the top level of the included `yml` block are doubled
> fix: misc startingpoint heads-up blog fixes

- .github/workflows/deploy.yml
To catch invalid links in the navigation section of the website, we could use the `--strict` flag which should turn warning into errors. This should catch something like this:
https://github.com/ublue-os/website/actions/runs/6164187895/job/16729371704#step:10:32
More info here:
https://www.mkdocs.org/user-guide/configuration/#validation
> fix: use strict build to catch invalid nav links

- docs/images/bluefin/framework.md
We link to certain configuration files shipped in the `bluefin-framework` image, but didn't update them after the switch to `/usr/etc` which leads to files not found when a user clicked the links.
> fix: use correct links in bluefin-framework

- docs/images/bazzite/installation.md
I have seen at least 1 Youtube comment asking how much storage is needed for Bazzite.  
In my own testing, a 16GB drive would NOT get past the Bazzite Portal first-boot setup phase, but a 32GB VM installation was fine.  I compromised with 20GB as a hard minimum system requirement.
> feat: add storage requirement

- docs/images/bazzite/FAQ.md
Also added:
- more details on rpm-ostree, but still have the link to Fedora's documentation as the first thing the user sees.
- how to rebase images.
- added troubleshooting tips under the issues section.
> fix: grammar on FAQ doc

- docs/guide/just.md
As mentioned here: https://github.com/ublue-os/website/issues/493
I am not sure if all of this information is accurate or correct, so please suggest any changes for me.  I also moved the `just enroll-secure-boot-key` under the Nvidia Images header, but this may be incorrect on my part.
> fix: Just page

- docs/images/bluefin/developer-experience.md
I'm not sure if there was an intention to link to a certain place or not. But the link is not there, so I removed the brackets. If the intention was to link to a page, please add in via review.
> fix: missed typo in bluefin-dx page

- docs/images.md
Would love feedback on this.  I am suggesting we should start to breakdown and categorize these images based on their purpose.  
I know there might still be confusion on the naming to follow Fedora's current naming scheme, so that might be something I will consider down the road too.  I would like to have users to be able to pick an image and know exactly what all of their choices are what each image means eventually.
For now, I offer categorization.  Please let me know what should be improved or if this whole idea should be scrapped and/or moved elsewhere.
> feat: Add Image Categorization Section

- docs/blog/.authors.yml
So it shows up on the next newsletters and every newsletter after.
> chore: Update nicknamenamenick's name

- .github/workflows/deploy.yml
This maybe the cause of the deployment being canceled when a PR is being merged into the main branch.
`Canceling since a higher priority waiting request for 'pages' exists`
Also bring back the on push branch main
```
push:
branches:
- main
```
Not 100% sure, but worth a shot.
> chore(ci): disable cancel-in-progress

- docs/blog/posts/bluefin-one-point-oh-rc.md
The related link on the `bluefin-one-point-oh-rc.md` blogpost was titled bazzite instead of bluefin.
> fix: change related link title to bluefin

- docs/guide/codecs.md
- docs/guide/just.md
- docs/images/nvidia.md
- Fixed a few outdated links.
- Updated syntax for some example commands (`just` commands & running containers with GPU access).
- Clarified that RPM Firefox users need to set some of the same env variables as is recommended for the Flatpak versions. Otherwise, the codecs would show up in Firefox about:support (the current recommendation for checking whether it's "working"), but Firefox would still default to software decoding.
> Update some nvidia-related commands and links.

- docs/images/bazzite/FAQ.md
It is now replaced with `ublue-update`.
chore: clarify updates a little better
> chore: Remove all mention of just update

- docs/blog/posts/bluefin-one-point-oh-rc.md
We released a newer beta iso a few days after the written blogpost. If people decide to get the iso from the link after reading the blogpost, lets point them to the latest version which has some small changes in it. 
I think it was things like `just update` changes.
> chore: update bluefin.iso link

- docs/guide/codecs.md
This will help people find the ffmpeg-full runtime version needed for enabling HW in a certain program.
> Added info to codecs guide

- docs/images/nvidia.md
The Firefox flatpak in Flathub uses version 22.08 of org.freedesktop.platform runtime. This is unable to interface with the nvidia video decoding driver as it was compiled using an older version of glibc. [more info](https://github.com/elFarto/nvidia-vaapi-driver/issues/23#issuecomment-1667177811)
> Add workaround for F39 nvidia firefox flatpak

- docs/images/surface.md
Surface images no longer use this
> fix: remove tlp documentation

- docs/tinker/setup/auto-cli.md
As the create-ublue-image tool evolves, it is possible that users could end up running an older version of the tool when setting up a new custom ublue image. Supplying `--pull=newer` to the `podman run` command ensures that users should always get the latest image when the command is run.
> chore: use `--pull=newer` for create-ublue-image

- docs/CONTRIBUTING.md
Discourse is now linked instead of Github Discussions
> fix: link in CONTRIBUTING

- docs/guide/toolbox.md
They redirected to the correct links anyways, but it's better this way.
> fix: broken links

- docs/cheatsheet/ostree.md
`sudo` is not necessary for most `rpm-ostree` commands. See https://coreos.github.io/rpm-ostree/administrator-handbook/ for full documentation.
> docs: remove unnecessary sudo for rpm-ostree

- docs/index.md
- docs/tinker.md
This PR should be merged right after the custom image tooling -related repositories are moved. https://github.com/ublue-os/main/issues/476
The "toolkit" card is also removed from the front page. Y'all can decide whether to add something similar back talking about something adjacent.
If someone wishes to review the referenced blog post before it is published, it can be read right here: https://github.com/blue-build/website/pull/28/files#diff-7b9d9b0968b0ff050f433578e787cacfa5f0526c908c1848ccd41d1591859207
> chore: tooling migration -related changes
